version: '3.7'

services:
  identity-notary:
    container_name: identity-notary
    restart: always
    build:
      context: ./identity-providers/
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "npm run start:notary"

  identity-clinic:
    container_name: identity-clinic
    restart: always
    build:
      context: ./identity-providers/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on: 
      - identity-notary
    command: "npm run start:clinic"

  identity-insurance:
    container_name: identity-insurance
    restart: always
    build:
      context: ./identity-providers/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - identity-notary
    command: "npm run start:insurance"

  identity-user:
    container_name: identity-user
    restart: always
    build:
      context: ./identity-providers/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - identity-notary
      - identity-clinic
      - identity-insurance
    command: "npm run start:user"

  wallet-ui:
    container_name: wallet-ui
    restart: always
    build:
      context: ./wallet-ui/
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - identity-user
    command: "npm run serve"

networks:
  default: