apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-insurance
  labels:
    app: identity-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-insurance
  template:
    metadata:
      labels:
        app: identity-insurance
    spec:
      containers:
        - name: identity-insurance
          image: rg.fr-par.scw.cloud/affectionatenewton/identity-image:latest
          command: ["npm", "run", "start:insurance"]
          env:
          - name: HTTPS_PORT
            value: "443"
          - name: HTTP_PORT
            value: "8080"
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
      imagePullSecrets:
        - name: registry-secret